# mysql
spring.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库1
    db1:
      jdbc-url: jdbc:mysql://192.168.0.14:3306/uyiban_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 1qazse4
    #数据库2
    db2:
      jdbc-url: jdbc:mysql://192.168.0.14:3306/uyiban_leave?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 1qazse4

spring:
  redis:
    database: 0
    host: 192.168.0.18
    port: 6379
    timeout: 10
#  ################ Redis 线程池设置 ##############
#  # 连接池最大连接数（使用负值表示没有限制） 默认 8
#  spring.redis.lettuce.pool.max-active=8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#  spring.redis.lettuce.pool.max-wait=-1
#  # 连接池中的最大空闲连接 默认 8
#  spring.redis.lettuce.pool.max-idle=8
#  # 连接池中的最小空闲连接 默认 0
#  spring.redis.lettuce.pool.min-idle=0
#

  cache:
    type: redis
    redis:
      cache-null-values: true
#  redis:
#    redisson:
#      config: classpath:redisson/redisson.yml
  logging:
    config: classpath:logback/logback-dev.xml
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

page helper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true


